# Generated by Django 5.2.4 on 2025-07-05 20:14

from django.db import migrations


class Migration(migrations.Migration):
    """Migration to rename the 'chat_id' field to 'chat' in ChatMessage model."""

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="chat_id",
            new_name="chat",
        ),
    ]
