"""Generated by Django 5.2.3 on 2025-06-22 12:30."""

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to alter the 'id' field of the User model to use UUIDs."""

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
