# Generated by Django 5.2.4 on 2025-07-05 19:29

import uuid

from django.db import migrations, models

import apps.chat.models


class Migration(migrations.Migration):
    """Migration to create the Chat and ChatMessage models."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default=apps.chat.models.default_chat_title,
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chats",
                "verbose_name_plural": "Chats",
                "db_table": "chats",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chat_messages",
                "verbose_name_plural": "Chat_messages",
                "db_table": "chat_messages",
            },
        ),
    ]
